INFO 2021-09-11 16:16:28,866 Watching for file changes with StatReloader
INFO 2021-09-11 16:17:34,005 Watching for file changes with StatReloader
ERROR 2021-09-11 16:18:08,923 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.all(current=True)
TypeError: all() got an unexpected keyword argument 'current'
ERROR 2021-09-11 16:18:08,952 "GET / HTTP/1.1" 500 62463
ERROR 2021-09-11 16:18:10,992 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.all(current=True)
TypeError: all() got an unexpected keyword argument 'current'
ERROR 2021-09-11 16:18:10,996 "GET /favicon.ico HTTP/1.1" 500 62147
INFO 2021-09-11 16:19:45,222 /home/ogaba/Desktop/school/apps/departments/middleware.py changed, reloading.
INFO 2021-09-11 16:20:16,045 Watching for file changes with StatReloader
ERROR 2021-09-11 16:20:21,414 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.departments.models.AcademicSession.DoesNotExist: AcademicSession matching query does not exist.
ERROR 2021-09-11 16:20:21,450 "GET / HTTP/1.1" 500 71363
ERROR 2021-09-11 16:20:23,116 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.departments.models.AcademicSession.DoesNotExist: AcademicSession matching query does not exist.
ERROR 2021-09-11 16:20:23,118 "GET /favicon.ico HTTP/1.1" 500 71129
INFO 2021-09-11 16:22:24,852 /home/ogaba/Desktop/school/apps/departments/urls.py changed, reloading.
INFO 2021-09-11 16:22:26,960 Watching for file changes with StatReloader
INFO 2021-09-11 16:22:41,714 "GET /admin HTTP/1.1" 301 0
ERROR 2021-09-11 16:22:41,923 Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.departments.models.AcademicSession.DoesNotExist: AcademicSession matching query does not exist.
ERROR 2021-09-11 16:22:41,929 "GET /admin/ HTTP/1.1" 500 71280
ERROR 2021-09-11 16:22:43,004 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ogaba/Desktop/school/apps/departments/middleware.py", line 9, in __call__
    current_session = AcademicSession.objects.get(current=True)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ogaba/anaconda3/envs/school/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.departments.models.AcademicSession.DoesNotExist: AcademicSession matching query does not exist.
ERROR 2021-09-11 16:22:43,006 "GET /favicon.ico HTTP/1.1" 500 71135
